// Label text bitmap: the two label-bar strips ("DOWN"/"FIELD POSITION"/
// "YARDS TO GO" and "HOME"/"TIME REMAINING"/"VISITOR"), stored as a small
// indexed bitmap (16-color palette) rather than a full-canvas image --
// see docs/superpowers/specs/2026-07-26-bezel-overlay-design.md for the
// memory-budget rationale. Generated by tools/gen_label_bitmap.py from
// assets/bezel/overlay_502x360.png.
module label_rom (
    input  wire [8:0]  x,       // 0-501
    input  wire [5:0]  band_y,  // 0-57
    output wire [23:0] rgb
);
    reg [3:0]  pixel_idx [0:29115];
    initial $readmemh("label_bitmap.mem", pixel_idx);

    reg [23:0] palette [0:15];
    initial $readmemh("label_palette.mem", palette);

    // Operands explicitly widened to the 15-bit result width (max value
    // 57*502+501 = 29115, fits in 15 bits) so Verilator's -Wall self-
    // determined-width check sees no implicit expansion/truncation
    // (already hit a similar case once this project, in rom_loader.v's
    // byte_sel_rev -- see its comment).
    wire [14:0] addr = ({9'd0, band_y} * 15'd502) + {6'd0, x};
    assign rgb = palette[pixel_idx[addr]];
endmodule
