// Label text bitmap: the two label-bar strips ("DOWN"/"FIELD POSITION"/
// "YARDS TO GO" and "HOME"/"TIME REMAINING"/"VISITOR"), stored as a small
// indexed bitmap rather than a full-canvas image -- see
// docs/superpowers/specs/2026-07-26-bezel-overlay-design.md for the
// memory-budget rationale. 128 colors (vs an earlier 16) to preserve
// anti-aliased text edges -- 16 colors collapsed partial-coverage edge
// pixels to solid foreground, making the text look artificially bold.
// Generated by tools/gen_bezel_bitmaps.py from
// assets/bezel/overlay_400x360.png (letterboxed, uniform-scale canvas;
// see docs/verification.md for the bring-up history behind these
// dimensions).
module label_rom (
    input  wire [8:0]  x,       // 0-399
    input  wire [4:0]  band_y,  // 0-19: 0-9 = bar1, 10-19 = bar2
    output wire [23:0] rgb
);
    reg [6:0]  pixel_idx [0:7999];
    initial $readmemh("label_bitmap.mem", pixel_idx);

    reg [23:0] palette [0:127];
    initial $readmemh("label_palette.mem", palette);

    // Operands explicitly widened to the 13-bit result width (max value
    // 19*400+399 = 7999, fits in 13 bits) so Verilator's -Wall self-
    // determined-width check sees no implicit expansion/truncation
    // (already hit a similar case once this project, in rom_loader.v's
    // byte_sel_rev -- see its comment).
    wire [12:0] addr = ({8'd0, band_y} * 13'd400) + {4'd0, x};
    assign rgb = palette[pixel_idx[addr]];
endmodule
