// APF bridge-loaded ROM for the B6100 core. The SD-card-supplied file
// (sim/roms/mfootb.bin, copied to Assets/<platform>/common/mfootb.bin on
// the Pocket) is 896 contiguous bytes; APF writes it verbatim, one 32-bit
// word at a time, starting at bridge address SLOT_BASE (matches data.json's
// "address": "0x10000000"). The CPU's own 10-bit address space has a hole
// (0x300-0x37F unmapped -- see b6100_cpu.v / the B6100's real ROM map), so
// reads translate CPU address -> dense file-offset index; writes need no
// such translation since the file itself has no hole.
module rom_loader #(
    parameter [31:0] SLOT_BASE = 32'h10000000
) (
    input  wire        clk,
    input  wire        bridge_wr,
    /* verilator lint_off UNUSEDSIGNAL */
    input  wire [31:0] bridge_addr,
    /* verilator lint_on UNUSEDSIGNAL */
    input  wire [31:0] bridge_wr_data,
    input  wire [9:0]  rom_addr,
    output wire [7:0]  rom_data
);
    // 896 bytes = 224 32-bit words, addressed 0..223 (8 bits)
    reg [31:0] mem [0:223];

    wire in_slot = (bridge_addr[31:24] == SLOT_BASE[31:24]);
    wire [7:0] wr_word_idx = bridge_addr[9:2];

    always @(posedge clk)
        if (bridge_wr && in_slot)
            mem[wr_word_idx] <= bridge_wr_data;

    // hole translate: CPU addresses 0x380-0x3FF are file offsets 0x300-0x37F
    // (the 0x300-0x37F CPU range is simply never generated by the CPU, per
    // the B6100's own program counter behavior, so no defensive clamping
    // is needed beyond this arithmetic)
    wire [9:0] dense_addr = (rom_addr >= 10'h380) ? (rom_addr - 10'h80) : rom_addr;
    wire [7:0] rd_word_idx = dense_addr[9:2];
    wire [1:0] byte_sel = dense_addr[1:0];

    // APF packs each bridge write big-endian (file byte 0 of a 4-byte
    // group lands in bits[31:24], not bits[7:0]) -- confirmed on real
    // hardware via a debug readback: byte_sel==0 was returning file byte 3
    // instead of file byte 0. Select from the high end to match.
    wire [1:0] byte_sel_rev = ~byte_sel;
    assign rom_data = mem[rd_word_idx][byte_sel_rev*8 +: 8];
endmodule
